### ISSUE TITLE
I2C seems to not work

### ISSUE THREAD

**Issue by techlab4kids-apps** [lifely-cc/agruminoLemon-libraries#1]
Hi all.
Giancarlo here :-)
I'm trying to interface an Agrumino board (repors 51/18 next to the CE mark).
I tried different sensors (with both grove and QT/STEMMA connector) but they are never detected bay the board.
I read the articles from https://www.hackster.io/ and (connection type apart) I cannot see evident mistakes by me.
Nevertheless my boards are obviously different from the one used in these articles (is the green one).

What can I do to solve my problem?

Thanks in advance.
Giancarlo

**Comment by TorgeTorge** [comment]
i'm having the same error....

> Hi all. Giancarlo here :-) I'm trying to interface an Agrumino board (repors 51/18 next to the CE mark). I tried different sensors (with both grove and QT/STEMMA connector) but they are never detected bay the board. I read the articles from https://www.hackster.io/ and (connection type apart) I cannot see evident mistakes by me. Nevertheless my boards are obviously different from the one used in these articles (is the green one).
> 
> What can I do to solve my problem?
> 
> Thanks in advance. Giancarlo

**Comment by broccia** [comment]
Hi @TorgeTorge,
If you're powering the I2C device through Agrumino (3V only) be sure to turn on the microswitch SW1-2.
Moreover please check if you're calling:
```
  agrumino.setup();
  agrumino.turnBoardOn();
```
before initializing your I2C device.

If this doesn't fix your issues please share your code so I can take a look :)

**Comment by TorgeTorge** [comment]
> Hi @TorgeTorge, If you're powering the I2C device through Agrumino (3V only) be sure to turn on the microswitch SW1-2. Moreover please check if you're calling:
> 
> ```
>   agrumino.setup();
>   agrumino.turnBoardOn();
> ```
> 
> before initializing your I2C device.
> 
> If this doesn't fix your issues please share your code so I can take a look :)

Grazie per la risposta. In realtà in problema è un altro, mi sono confuso con il messaggio precedente. In pratica non riesco a caricare alcun codice su Agrumino, in quanto compare sempre questo messaggio di errore durante la compilazione:
`In file included from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\Agrumino.cpp:15:
c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/PCA9536/PCA9536.cpp:36:7: warning: 'asm' qualifier 'volatile' ignored outside of function body
   36 | __asm volatile ("nop");
      |       ^~~~~~~~
In file included from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/PCA9536/PCA9536.cpp:39,
                 from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\Agrumino.cpp:15:
c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/PCA9536/PCA9536.h:119:7: warning: 'asm' qualifier 'volatile' ignored outside of function body
  119 | __asm volatile ("nop");
      |       ^~~~~~~~
In file included from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/PCA9536/PCA9536.h:128,
                 from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/PCA9536/PCA9536.cpp:39,
                 from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\Agrumino.cpp:15:
c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/PCA9536/utility/PCA9536_PString.h:7:7: warning: 'asm' qualifier 'volatile' ignored outside of function body
    7 | __asm volatile ("nop");
      |       ^~~~~~~~
In file included from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\Agrumino.cpp:16:
c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/MCP3221/MCP3221.cpp:36:7: warning: 'asm' qualifier 'volatile' ignored outside of function body
   36 | __asm volatile ("nop");
      |       ^~~~~~~~
In file included from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/MCP3221/MCP3221.cpp:39,
                 from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\Agrumino.cpp:16:
c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/MCP3221/MCP3221.h:126:7: warning: 'asm' qualifier 'volatile' ignored outside of function body
  126 | __asm volatile ("nop");
      |       ^~~~~~~~
In file included from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/MCP3221/MCP3221.h:135,
                 from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/MCP3221/MCP3221.cpp:39,
                 from c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\Agrumino.cpp:16:
c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\libraries/MCP3221/utility/MCP3221_PString.h:7:7: warning: 'asm' qualifier 'volatile' ignored outside of function body
    7 | __asm volatile ("nop");
      |       ^~~~~~~~
c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\Agrumino.cpp: In member function 'unsigned int Agrumino::readGPIO(gpio_pin)':
c:\Users\nick\Documents\Arduino\libraries\Lifely_Agrumino_Lemon\Agrumino.cpp:246:42: error: control reaches end of non-void function [-Werror=return-type]
  246 |     Serial.println("Error! gpio pin [" + String(pin) + "] is not set as OUTPUT, unable to write");
      |                                          ^~~~~~~~~~~
cc1plus.exe: some warnings being treated as errors

exit status 1

Compilation error: exit status 1`

**Comment by Bighoneypot** [comment]
Hi dear @techlab4kids-apps ,
Can you share with us your code?
Which IDE do you use ? Version? S.O.?

I need to reproduce your error, thanks for your report.

**Comment by Bighoneypot** [comment]
Dear @TorgeTorge  please follow this: [https://github.com/lifely-cc/agruminoLemon-libraries/issues/2](url) 

I need some info about:
IDE version,
Lifely Agrumino Lemon Version,
if is possible, your code.


Please, write this in new issue [https://github.com/lifely-cc/agruminoLemon-libraries/issues/2 ]

Thank you
